package JAVAGUI.PracticeExercise1;

import javax.swing.*;

public class Login {
    public static void main(String[] args) {
        //Creating object of LoginFrame class and setting some of its properties
        JavaFrame frame = new JavaFrame();
        frame.setTitle("Login Form");
        frame.setVisible(true);
        frame.setBounds(10,10,370,400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
}

}